version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    logging:
      driver: none
    volumes:
      - "./datadir:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  server:
    build: ./server
    restart: always
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      CONTEXT: mongodb

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/react
    depends_on:
      - server
